### PR TITLE
Update the tools for the 2016 anneal activity

### PR DESCRIPTION
**Pull request by jeanconn**
Update the tools for the 2016 anneal activity

### CODE REVIEW

**Comment by taldcroft** [comment]
Are we going to do a two-hop SSH from a GRETA machine to aca@coot, or use a laptop?  We will want to have a standard EGSE version of splat (with images) running as well.

**Comment by jeanconn** [comment]
> Are we going to do a two-hop SSH from a GRETA machine to aca@coot, or use
> a laptop? We will want to have a standard EGSE version of splat (with
> images) running as well.

​I was planning on the laptop with the two-hop SSH as a backup if anything
went screwy with the VPN.

I had also planned to do the "with images" from this one copy of splat, but
could certainly do it from the standard EGSE edition if preferred.​

**Comment by taldcroft** [comment]
Sounds good.

**Comment by taldcroft** [comment]
:+1: on the PR.

**Pull request merged**
