### PR TITLE
Need to flush output in splat

### PR DESCRIPTION
**Pull request by jeanconn**
When I run data coming into splat at near real time then it can take a minute or so to get the new pixel values written to file.  Presumably the file handled needs to be flushed each update.

### CODE REVIEW

**Comment by jeanconn** [comment]
I was slightly concerned about this, but was focusing on your "splat unmodified" directive.

It has been a while since I've dealt with Perl buffering; do you want to use IO::Handle to flush/ autoflush, unbuffer with $|, use binmode to make the file unbuffered, or close the file on every write?

**Comment by jeanconn** [comment]
Actually, it looks like autoflush is already set, so maybe explicit flushing...

**Comment by jeanconn** [comment]
The real problem I'm having is I can't seem to replicate the problem.

**Comment by jeanconn** [comment]
In my test, I'm running dump2occ.py on a file and piping it to splat, and if I tail -f the output acaslot6.dat file, I see new values on every tail refresh.

**Comment by jeanconn** [comment]
Ah, but the realtimeproblem is a different problem, right?  It is not the problem of too much data but too little.  OK.  I can figure this out.

**Comment by taldcroft** [comment]
I'm running splat on coot and then tail -f on kadi and seeing this buffering.  It isn't a showstopper but not ideal.  Are you running differently?

**Comment by jeanconn** [comment]
Code attached that does 'sync' ing which seems to help.  And I'm running splat on baffin and tailing the file on fido that I'm writing to /proj/sot/ska.

**Comment by taldcroft** [comment]
OK that helps.

**Pull request merged**
