### PR TITLE
Set correct $ACA_DECOM_HOME

### PR DESCRIPTION
**Pull request by jeanconn**
Are we planning to run the code from a GRETA machine or from coot/unagi/baffin?

### CODE REVIEW

**Comment by jeanconn** [comment]
I think this should just be

"$ENV{SKA}/data/aca_egse/decom/aca"

and not the 

"$ENV{SKA}/decom/aca"

on the splat that is from the mercurial egse repo

**Comment by taldcroft** [comment]
For the record, coot or unagi.

**Comment by taldcroft** [comment]
On the recent question, I don't know without any context, but your first choice looks better in general.

**Comment by jeanconn** [comment]
And it exists on the systems in question.

**Pull request merged**
