### PR TITLE
Add exception handling on sherpa failures

### PR DESCRIPTION
**Pull request by jeanconn**
Add exception handling on sherpa failures

### CODE REVIEW

**Comment by taldcroft** [comment]
You can do lines 37-45 in one line with pyyaks.logger.  It's there for a reason!
http://cxc.harvard.edu/contrib/pyyaks/logger.html#pyyaks.logger.get_logger

**Comment by taldcroft** [comment]
In line 216 why are you putting the failed fit info into the `sherpa` log?  Shouldn't it be going to our application log (to console and log file)?

**Comment by taldcroft** [comment]
Good apart from comments.

**Comment by jeanconn** [comment]
I don't think the 37-45 is strictly a comment on this PR, but sure, I could use pyyaks.  I don't really know what is in there.  Rainy day reading.   Biggest problem is just that I tend to develop in ipython, and if I don't conditionally control the handlers, I keep adding handlers every time I call the script.

**Comment by jeanconn** [comment]
For line 216, I didn't actually care about logging the failures to the log file, so using the sherpa log kept it on console.

**Comment by taldcroft** [comment]
You found another reason I didn't even know about to use pyyaks.

```
In [6]: l = pyyaks.logger.get_logger(name='mylogger')
In [7]: l.info('hey')
hey

In [8]: l = pyyaks.logger.get_logger(name='mylogger')
In [9]: l.info('hey')
hey
```

**Comment by jeanconn** [comment]
Huh.  I ended up with three loggers writing to my file...

**Comment by jeanconn** [comment]
I'll add that to my rainy day debugging.

**Comment by taldcroft** [comment]
> Huh. I ended up with three loggers writing to my file...

???

```
In [10]: l = pyyaks.logger.get_logger(name='mylogger', filename='test.log')

In [11]: l.info('hey')
hey

In [12]: l = pyyaks.logger.get_logger(name='mylogger', filename='test.log')

In [13]: l.info('hey')
hey

In [14]: l.info('hey2')
hey2

In [15]: more test.log
hey
hey2

In [16]: l = pyyaks.logger.get_logger(name='mylogger', filename='test.log')

In [17]: l.info('hey3')
hey3

In [18]: more test.log
hey3
```

**Comment by taldcroft** [comment]
Ah, I was not using `filemode='a'`.  Hmm.

**Comment by taldcroft** [comment]
No, it still does the right thing AFAIK:

```
In [19]: l = pyyaks.logger.get_logger(name='mylogger', filename='test.log', filemode='a')

In [20]: l.info('hey4')
hey4

In [21]: l = pyyaks.logger.get_logger(name='mylogger', filename='test.log', filemode='a')

In [22]: l.info('hey5')
hey5

In [23]: more test.log
hey3
hey4
hey5
```

**Comment by jeanconn** [comment]
Yeah.  I can't seem to repeat my failure.

**Comment by jeanconn** [comment]
But so you don't think me nuts, I can at least append some of my file output.  Someday I'll try to reconstruct it.

```
*************************************************
*************************************************
*************************************************
*************************************************
Time = 2015:248:16:06:42.336
Time = 2015:248:16:06:42.336
Time = 2015:248:16:06:42.336
Time = 2015:248:16:06:42.336
CCD temperature = -14.99
CCD temperature = -14.99
CCD temperature = -14.99
CCD temperature = -14.99
Slot = 6.0

Slot = 6.0

Slot = 6.0

Slot = 6.0
```

**Pull request merged**
